{age: 0, language: spanish, startWith: gemini, tokenAPIai: 1ea8426077614af3967e148fe566ab61, op_question: yes, volume: 100, gassistant_proyectid: brogiebot, geminiAPI: AIzaSyAScHaoycBlr80cdA4yU09mR41bCJYba2I }
